### ISSUE TITLE
MacOS Ventura 13.5.2 Can not import .blend file 

### ISSUE THREAD

**Issue by SomjadeLykkeStudio** [antonWetzel/BlenderHelper#2]
MacOS Ventura 13.5.2
Can not import .blend file (Already entered path to Blender app in Project's Setting
![Screenshot 2566-10-12 at 00 37 28](https://github.com/antonWetzel/BlenderHelper/assets/114128105/e4f008f6-7438-49f9-add5-bff6c7eba409)

![Screenshot 2566-10-12 at 00 39 26](https://github.com/antonWetzel/BlenderHelper/assets/114128105/34a889cb-272d-47fc-89b2-43bf67cfb7a5)

**Comment by antonWetzel** [comment]
This extension is abandoned, because the engine has built in blender import now.

Don't use this extenions and follow the guide https://docs.godotengine.org/en/stable/tutorials/assets_pipeline/importing_scenes.html#importing-blend-files-directly-within-godot.

**Comment by Uradamus** [comment]
For what it's worth, Godot does not at all have built-in .blend import. What it does is when you drop a .blend file into your project dir, it starts up Blender in the background, and has that export the contents of your .blend file using the gltf exporter with default settings, and lets you go on believing Godot has imported the .blend file, when in reality it brought it in as a gltf with all of the usual problems that come with that garbage format.

Still better than Collada at least, but no where near as good as something tailor made for a Blender to Godot pipeline, which this had some real potential to be. Since the official .escn addon got abandoned a few years back when they decided to take the easy (for them) route of using gltf for nearly everything, that is now basically the only way to get stuff in and its awful. Even the FBX "importer" is the same setup, just a different 3rd party tool in the background spitting out a GLTF file.

I really wish they stuck with that .escn importer as the first class method for getting 3D assets into Godot. It would work for everyone since Blender is free and supports a much wider selection of import options, so can easily be used as an intermediary for anyone using other software as well. They could keep the crappy GLTF support around for those who insist on using it, but really the energy should be going towards a much better and more focused solution to make getting stuff from Blender to Godot as painlessly as possible.
